services:
  pixelartapp:
    image: gtk-python:latest
    build:
      context: .
      dockerfile: gpu.Dockerfile
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - DISPLAY=${DISPLAY:-host.docker.internal:0.0}
    env_file:
      - env.txt
    volumes:
      - .:/app:cached
    stdin_open: true
    tty: true
    command: python3 main.py